# ==============================================================================
# Snakemake workflow: Preprocessing of Illumina sequencing data 
#                     containing unique molecular identifiers (UMIs)
#
# Author: Raphael Hablesreiter (raphael.hablesreiter@charite.de)
# modified by Hanna Edler, 04-09-2024
#
# Description:
# Snakemake implementation of IDT analysis guidelines "Demultiplexing Illumina 
# sequencing data containing unique molecular identifiers (UMIs)".
# ==============================================================================

# ==============================================================================
# Initialization of workflow
# ==============================================================================

import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

min_version("8.10")

configfile: "../config/P3471/configP3471.yaml"
validate(config, schema="schemas/config.schema.yaml")

SAMPLES = os.listdir(config["general"]["work_dir"] + "/demux/unmapped/")
SAMPLES = list(filter(lambda x:'.unmapped.bam' in x, SAMPLES))
SAMPLES = [s.replace('.unmapped.bam', '') for s in SAMPLES]
print(SAMPLES) #can cause problems when visualizing the DAG with dot; simply comment out

workdir: config["general"]["work_dir"] + "/demux/"

# ==============================================================================
# Include rules
# ==============================================================================

include: "rules/resources.smk"
include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/tools.smk"

# ==============================================================================
# Results
# ==============================================================================

rule all:
    input:
        "logs/save/preprocess/done.txt"
